In [57]:
import keras
print(keras.__version__)

2.2.4


In [58]:
import numpy as np
np.random.seed(1337)  # for reproducibility
from keras.datasets import mnist
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import RMSprop
from keras.models import load_model


- models.Sequential，用来一层一层一层的去建立神经层；
- layers.Dense 意思是这个神经层是全连接层。
- layers.Activation 激励函数。
- optimizers.RMSprop 优化器采用 RMSprop，加速神经网络训练方法。

In [59]:
from keras.datasets import mnist
from keras import utils as np_utils

# download the mnist to the path '~/.keras/datasets/' if it is the first time to be called
# X shape (60,000 28x28), y shape (10,000, )
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# data pre-processing
X_train = X_train.reshape(X_train.shape[0], -1) / 255.   # normalize
X_test = X_test.reshape(X_test.shape[0], -1) / 255.      # normalize
y_train = np_utils.to_categorical(y_train, num_classes=10)
y_test = np_utils.to_categorical(y_test, num_classes=10)

print(X_train[1].shape)
"""
(784,)
"""

print(y_train[:3])
"""
[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]
"""


(784,)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


'\n[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]\n [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]\n [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]\n'

In [60]:
# Another way to build your neural net
model = Sequential([
    Dense(32, input_dim=784),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])


In [61]:
# Another way to define your optimizer
rmsprop = RMSprop(lr=0.001, rho=0.9, epsilon=1e-08, decay=0.0)


In [62]:
# We add metrics to get more results you want to see
model.compile(optimizer=rmsprop,
              loss='categorical_crossentropy',
              metrics=['accuracy'])


In [63]:
print('Training ------------')
# Another way to train the model
model.fit(X_train, y_train, epochs=5, batch_size=32)

Training ------------
Epoch 1/5
60000/60000 [==============================] - 5s 77us/step - loss: 0.3459 - acc: 0.9043
Epoch 2/5
60000/60000 [==============================] - 4s 66us/step - loss: 0.2000 - acc: 0.9423
Epoch 3/5
60000/60000 [==============================] - 4s 64us/step - loss: 0.1647 - acc: 0.9522
Epoch 4/5
60000/60000 [==============================] - 4s 64us/step - loss: 0.1446 - acc: 0.9586
Epoch 5/5
60000/60000 [==============================] - 4s 66us/step - loss: 0.1303 - acc: 0.9626


In [64]:
print('\nTesting ------------')
# Evaluate the model with the metrics we defined earlier
loss, accuracy = model.evaluate(X_test, y_test)

print('test loss: ', loss)
print('test accuracy: ', accuracy)


Testing ------------
10000/10000 [==============================] - 0s 36us/step
test loss:  0.14248259023595602
test accuracy:  0.9617


In [65]:
# save
print('test before save: ', model.predict(X_test[0:2]))
model.save('my_model.h5')   # HDF5 file, you have to pip3 install h5py if don't have it
del model  # deletes the existing model

"""
test before save:  [[ 1.87243938] [ 2.20500779]]
"""


test before save: [[1.6336678e-08 3.8133047e-10 4.0679852e-06 1.7156552e-04 1.1218182e-11
  2.1845781e-06 3.3652805e-14 9.9980968e-01 1.8032091e-07 1.2310393e-05]
 [1.8916332e-08 8.3443830e-08 9.9996877e-01 2.1627320e-05 1.5859114e-20
  9.5777732e-06 9.5562225e-10 5.0231379e-15 1.9747576e-08 9.8034290e-17]]


'\ntest before save:  [[ 1.87243938] [ 2.20500779]]\n'

In [68]:
# load
model = load_model('my_model.h5')
print('test after load: ', model.predict(X_test[0:2]))

test after load:  [[1.6336678e-08 3.8133047e-10 4.0679852e-06 1.7156552e-04 1.1218182e-11
  2.1845781e-06 3.3652805e-14 9.9980968e-01 1.8032091e-07 1.2310393e-05]
 [1.8916332e-08 8.3443830e-08 9.9996877e-01 2.1627320e-05 1.5859114e-20
  9.5777732e-06 9.5562225e-10 5.0231379e-15 1.9747576e-08 9.8034290e-17]]
