In [1]:
import keras
print(keras.__version__)

Using TensorFlow backend.


2.2.4


In [2]:
import numpy as np
np.random.seed(1337)  # for reproducibility
from keras.datasets import mnist
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import RMSprop
from keras.models import load_model


- models.Sequential，用来一层一层一层的去建立神经层；
- layers.Dense 意思是这个神经层是全连接层。
- layers.Activation 激励函数。
- optimizers.RMSprop 优化器采用 RMSprop，加速神经网络训练方法。

In [3]:
from keras.datasets import mnist
from keras import utils as np_utils

# download the mnist to the path '~/.keras/datasets/' if it is the first time to be called
# X shape (60,000 28x28), y shape (10,000, )
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# data pre-processing
X_train = X_train.reshape(X_train.shape[0], -1) / 255.   # normalize
X_test = X_test.reshape(X_test.shape[0], -1) / 255.      # normalize
y_train = np_utils.to_categorical(y_train, num_classes=10)
y_test = np_utils.to_categorical(y_test, num_classes=10)

print(X_train[1].shape)
"""
(784,)
"""

print(y_train[:3])
"""
[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]
"""


(784,)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


'\n[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]\n [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]\n [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]\n'

In [4]:
# Another way to build your neural net
model = Sequential([
    Dense(32, input_dim=784),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])


In [5]:
# Another way to define your optimizer
rmsprop = RMSprop(lr=0.001, rho=0.9, epsilon=1e-08, decay=0.0)


In [6]:
# We add metrics to get more results you want to see
model.compile(optimizer=rmsprop,
              loss='categorical_crossentropy',
              metrics=['accuracy'])


In [7]:
print('Training ------------')
# Another way to train the model
model.fit(X_train, y_train, epochs=5, batch_size=32)

Training ------------
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/5





60000/60000 [==============================] - 2s 29us/step - loss: 0.3435 - acc: 0.9045

In [8]:
print('\nTesting ------------')
# Evaluate the model with the metrics we defined earlier
loss, accuracy = model.evaluate(X_test, y_test)

print('test loss: ', loss)
print('test accuracy: ', accuracy)


Testing ------------
10000/10000 [==============================] - 0s 14us/step
test loss:  0.14012798573412
test accuracy:  0.9631


In [9]:
# save
print('test before save: ', model.predict(X_test[0:2]))
model.save('my_model.h5')   # HDF5 file, you have to pip3 install h5py if don't have it
del model  # deletes the existing model

"""
test before save:  [[ 1.87243938] [ 2.20500779]]
"""


test before save:  [[5.4451190e-09 1.8686803e-10 9.6930705e-07 2.3778816e-04 5.1135793e-12
  2.1742915e-06 3.1091547e-15 9.9974173e-01 1.0715156e-07 1.7168048e-05]
 [2.3252000e-09 1.1106925e-08 9.9999583e-01 3.9251941e-06 1.0919619e-19
  2.5412237e-07 2.7391059e-10 4.9488679e-15 1.6065025e-08 1.1021497e-16]]


'\ntest before save:  [[ 1.87243938] [ 2.20500779]]\n'

In [10]:
# load
model = load_model('my_model.h5')
print('test after load: ', model.predict(X_test[0:2]))

test after load:  [[5.4451190e-09 1.8686803e-10 9.6930705e-07 2.3778816e-04 5.1135793e-12
  2.1742915e-06 3.1091547e-15 9.9974173e-01 1.0715156e-07 1.7168048e-05]
 [2.3252000e-09 1.1106925e-08 9.9999583e-01 3.9251941e-06 1.0919619e-19
  2.5412237e-07 2.7391059e-10 4.9488679e-15 1.6065025e-08 1.1021497e-16]]
