In [31]:
import tensorflow as tf

print(tf.__version__)

2.0.0


# 线性代数

本节目标：简单回忆线性代数的相关知识

## 矩阵 Matrices
A=\begin{pmatrix}
 a_{11} & a_{12} & \cdots & a_{1m} \\
 a_{21} & a_{22} & \cdots & a_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
 a_{n1} & a_{n2} & \cdots & a_{nm} \\
\end{pmatrix}

以下展示的是tf里的转置操作

In [32]:
A = tf.constant(range(10))
A = tf.reshape(A,[2,5])
print(A)
A = tf.transpose(A)
print(A)

tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]], shape=(5, 2), dtype=int32)


## 张量 Tensors
如果增加轴的数量，我们就获得了一个高维度的“张量”

In [33]:
A = tf.constant(range(24))
A = tf.reshape(A,[2,3,4])
print(A)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)


求和用到的是 tf.reduce_sum(),简单来说是按维度求和 
详见

In [34]:
print(tf.reduce_sum(A,0))
print(tf.reduce_sum(A,1))

tf.Tensor(
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[12 15 18 21]
 [48 51 54 57]], shape=(2, 4), dtype=int32)
