In [154]:
import tensorflow as tf

print(tf.__version__)

2.0.0


# 张量的基础操作

本节目标：了解张量的
- 创建
    - 从常量创建
    - 从numpy转换
    - 创建元素为指定值的tensor
    - 随机初始化
- 索引
    - 基础索引
    - 冒号切片索引
    - 维度选择：gather()和gather_nd()
    - 条件索引：真值判断 结合 where()
- 转换
    - 变形 reshape()
    - 转置 transpose()
    - 增加维度 expand_dims()
    - 删除维度 squeeze()

# 1 创建

# 1.1 constant()方法

In [155]:
tf.constant(1)  # 创建一个整型张量

<tf.Tensor: id=403, shape=(), dtype=int32, numpy=1>

In [156]:
tf.constant(1.)  # 创建一个浮点型张量

<tf.Tensor: id=404, shape=(), dtype=float32, numpy=1.0>

In [157]:
tf.constant(2., dtype=tf.double)  # 创建的同时指定数据类型

<tf.Tensor: id=405, shape=(), dtype=float64, numpy=2.0>

In [158]:
tf.constant([[1.,2.,3.],[4.,5.,6.]])  # 通过传入一个list参数创建

<tf.Tensor: id=406, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

如果输入的数据与指定的数据类型不相符，会产生以下异常：  
TypeError: Cannot convert provided value to EagerTensor. Provided value: 2.1 Requested dtype: int32

# 1.2 convert_to_tensor()方法

In [159]:
import numpy as np

In [160]:
tf.convert_to_tensor(np.ones([2, 3]))

<tf.Tensor: id=407, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [161]:
tf.convert_to_tensor(np.ones([2, 3]))

<tf.Tensor: id=408, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [162]:
tf.convert_to_tensor([[2.,3.],[3., 4.]])

<tf.Tensor: id=409, shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [3., 4.]], dtype=float32)>

# 1.3 创建元素为指定值的tensor

**（1）zeros()与ones()**

In [163]:
a = tf.zeros([2, 3, 3])  # 创建一个元素全为0，形状为[2, 3, 3]的tensor
print(a)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 3, 3), dtype=float32)


In [164]:
b = tf.ones([2, 3])  #  创建一个元素全为1，形状为[2, 3]的tensor
print(b)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


**（2）zeros_like()与ones_like**

In [165]:
tf.zeros_like(b)  # 仿照b的shape创建一个全为0的tensor

<tf.Tensor: id=416, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [166]:
tf.ones_like(a)  # 仿照b的shape创建一个全为1的tensor

<tf.Tensor: id=419, shape=(2, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

**（3）fill()**

In [167]:
tf.fill([2,3],5)  # 创建元素全为5，形状为[2,3]的tensor

<tf.Tensor: id=422, shape=(2, 3), dtype=int32, numpy=
array([[5, 5, 5],
       [5, 5, 5]])>

# 1.4 随机初始化

在实际应用中，经常需要随机初始化元素服从某种分布的tensor，TensorFlow中也提供了这种功能。  

**（1）从指定正态分布中随机取值：tf.random.normal()。**例如，随机初始化一个元素服从均值为1，方差为1的正态分布且形状为[2, 3]的tensor：

In [168]:
tf.random.normal([2, 3], mean=1, stddev=1) 

<tf.Tensor: id=428, shape=(2, 3), dtype=float32, numpy=
array([[1.6656713, 1.9298074, 1.718288 ],
       [1.2457561, 1.0986533, 2.43606  ]], dtype=float32)>

**（2）从指定的截断正态分布中随机取值：truncated_normal()。**意思是从指定的正太分布中取值，但是取值范围在两个标准差范围内，也就是：[ mean - 2 * stddev, mean + 2 * stddev ]

In [169]:
tf.random.truncated_normal([2, 3], mean=1, stddev=1)

<tf.Tensor: id=434, shape=(2, 3), dtype=float32, numpy=
array([[1.4711734, 2.512186 , 1.6642773],
       [1.7682488, 1.6989379, 1.1191772]], dtype=float32)>

**（3）从指定均匀分布中随机取值：tf.random.uniform()。**

In [170]:
tf.random.uniform([2, 3], minval=1, maxval=2) # 在1~2之间均匀分布

<tf.Tensor: id=441, shape=(2, 3), dtype=float32, numpy=
array([[1.8535746, 1.5019029, 1.0787992],
       [1.2431394, 1.5803543, 1.1491113]], dtype=float32)>

# 2 索引

In [171]:
a = tf.convert_to_tensor(np.arange(80).reshape(2,2,4,5))

In [172]:
a

<tf.Tensor: id=442, shape=(2, 2, 4, 5), dtype=int32, numpy=
array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]],


       [[[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]],

        [[60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74],
         [75, 76, 77, 78, 79]]]])>

# 2.1 基础索引

TensorFlow支持Python原生的基础索引方式，即多个方括号逐步索引取值：[idx][idx][idx]，每个方括号对应一个维度。

In [173]:
a[0]  # 取第一个维度

<tf.Tensor: id=446, shape=(2, 4, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])>

In [174]:
a[0][1]  # 同时筛选两个维度

<tf.Tensor: id=454, shape=(4, 5), dtype=int32, numpy=
array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])>

In [175]:
a[1][1][3]  # 同时对3个维度进行筛选

<tf.Tensor: id=466, shape=(5,), dtype=int32, numpy=array([75, 76, 77, 78, 79])>

这种索引数据的方法简单，易于理解，但是可读性差，只能按维度依次索引数据，也不能索引列。

# 2.2 numpy索引

TensorFlow也继承了numpy中的部分索引方式，这种索引方式是在一个方括号内写下所有的索引，每个索引序号之间用逗号隔开。

In [176]:
a[1]  # 筛选第一维度，这跟基础索引一样

<tf.Tensor: id=470, shape=(2, 4, 5), dtype=int32, numpy=
array([[[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]]])>

In [177]:
a[1,1, 3]  # 同时筛选3个维度

<tf.Tensor: id=474, shape=(5,), dtype=int32, numpy=array([75, 76, 77, 78, 79])>

**（2）冒号切片与步长：[start:end:step]**

这种索引方式在Python原生的list类型中也是常见的，而且使用方法也是一样的。

In [178]:
a[1,:,0:2] # 对第1维度选第二块数据，对第二维度选所有数据，对第三维度选前两行

<tf.Tensor: id=478, shape=(2, 2, 5), dtype=int32, numpy=
array([[[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])>

In [179]:
a[1,:,0:2,0:4] # 继续上面的例子，对第4维度筛选去前4列

<tf.Tensor: id=482, shape=(2, 2, 4), dtype=int32, numpy=
array([[[40, 41, 42, 43],
        [45, 46, 47, 48]],

       [[60, 61, 62, 63],
        [65, 66, 67, 68]]])>

In [180]:
a[1,:,0:2,0:4:2] # 对第4维度加上步长，每隔一个数据取一次

<tf.Tensor: id=486, shape=(2, 2, 2), dtype=int32, numpy=
array([[[40, 42],
        [45, 47]],

       [[60, 62],
        [65, 67]]])>

也可以使用负值步长表示逆序索引，但要注意，负数步长时，原本的[start : end : step]也要跟着编程[end : start : step]：

In [181]:
a[1,:,0:2,4:0:-1]

<tf.Tensor: id=490, shape=(2, 2, 4), dtype=int32, numpy=
array([[[44, 43, 42, 41],
        [49, 48, 47, 46]],

       [[64, 63, 62, 61],
        [69, 68, 67, 66]]])>

In [182]:
a[1,:,0:2,4:0:-2]

<tf.Tensor: id=494, shape=(2, 2, 2), dtype=int32, numpy=
array([[[44, 42],
        [49, 47]],

       [[64, 62],
        [69, 67]]])>

在numpy和TensorFlow中还有“..."（三个英文句号）的使用，“..."用于表示连续多个维度全选：

In [183]:
a[1,...,0:4] # 等同于a[1, : , : ,0:4]

<tf.Tensor: id=498, shape=(2, 4, 4), dtype=int32, numpy=
array([[[40, 41, 42, 43],
        [45, 46, 47, 48],
        [50, 51, 52, 53],
        [55, 56, 57, 58]],

       [[60, 61, 62, 63],
        [65, 66, 67, 68],
        [70, 71, 72, 73],
        [75, 76, 77, 78]]])>

In [184]:
a[0,0,...] # 等同于a[0,0,:,:]

<tf.Tensor: id=502, shape=(4, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])>

# 2.3 gather与gather_nd

gather与gather_nd是指TensorFlow通过gather()方法和gather_nd()方法提供的两种索引方式。在numpy中，可以通过嵌套list的方式来指定无规则的索引：

In [185]:
b = np.arange(20).reshape(4,5)

In [186]:
b[1, [0,3,4]] # 选取第2行的第1列、第4列、第5列

array([5, 8, 9])

但是在TensorFlow中，这种索引方式并没有从numpy中继承下来,所以如果在Tensor中使用这种方式，会抛出以下异常：  
TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got [0, 3, 4]

还好的是，在TensorFlow中通过gather()方法和gather_nd()方法提供了这种索引方法。

**（1）gather()方法**

In [187]:
tf.gather(b, axis=0, indices=[0, 2, 3]) # 选取第1行，第3行，第4行

<tf.Tensor: id=506, shape=(3, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])>

In [188]:
tf.gather(b, axis=1, indices=[0, 2, 3]) # 选取第1列，第3列，第4列

<tf.Tensor: id=510, shape=(4, 3), dtype=int32, numpy=
array([[ 0,  2,  3],
       [ 5,  7,  8],
       [10, 12, 13],
       [15, 17, 18]])>

仔细观察上面gather()方法例子，可以发现，第一个参数时数据源，还有两个参数中，axis指的是将要的维度，indices指的是需要选取的序号。

**（2）gather_nd()**

gather()方法一次只能对一个维度进行索引，gather_nd()方法可以同时对多个维度进行索引。

In [189]:
tf.gather_nd(b, [[0, 2],[3, 3]]) # 选取第1行第3列的那个数据，和第4行第4列的数据

<tf.Tensor: id=513, shape=(2,), dtype=int32, numpy=array([ 2, 18])>

# 2.4 条件索引

可以结合一些简单的逻辑运算符进行索引取值：

In [191]:
a = tf.random.uniform([3,3],minval=-10,maxval=10,dtype=tf.int32)
a

<tf.Tensor: id=517, shape=(3, 3), dtype=int32, numpy=
array([[  5,   9,  -3],
       [ -7,   3, -10],
       [  2,   6,   9]])>

In [192]:
mask = a < 0
mask

<tf.Tensor: id=519, shape=(3, 3), dtype=bool, numpy=
array([[False, False,  True],
       [ True, False,  True],
       [False, False, False]])>

可以看到，返回的是一个shape与a相同的tensor，在a小于零的位置是True，大于零的位置为False。进一步地，我们可以用boolwan_mask()方法直接取出符合条件的元素：

In [193]:
tf.boolean_mask(a,mask)

<tf.Tensor: id=546, shape=(3,), dtype=int32, numpy=array([ -3,  -7, -10])>

可以结合where()方法取出符合条件元素的索引：

In [194]:
m_index = tf.where(mask)
m_index

<tf.Tensor: id=547, shape=(3, 2), dtype=int64, numpy=
array([[0, 2],
       [1, 0],
       [1, 2]], dtype=int64)>

再使用之前说过的gather_nd()方法取值：

In [195]:
tf.gather_nd(a,m_index)

<tf.Tensor: id=548, shape=(3,), dtype=int32, numpy=array([ -3,  -7, -10])>

where()方法还有第二种用法——从两个tensor中取出符合条件的值，这时候where()方法必须接受3个参数：

In [196]:
condition = tf.random.uniform([3,3],minval=0,maxval=2,dtype=tf.int32)
condition = tf.cast(condition, tf.bool)
condition

<tf.Tensor: id=553, shape=(3, 3), dtype=bool, numpy=
array([[False, False,  True],
       [False,  True, False],
       [False,  True, False]])>

In [197]:
a = tf.range(1,10)
a = tf.reshape(a,[3,3])
a

<tf.Tensor: id=559, shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [198]:
b = tf.range(-9,0)
b = tf.reshape(b,[3,3])
b

<tf.Tensor: id=565, shape=(3, 3), dtype=int32, numpy=
array([[-9, -8, -7],
       [-6, -5, -4],
       [-3, -2, -1]])>

In [199]:
tf.where(condition, a, b)

<tf.Tensor: id=566, shape=(3, 3), dtype=int32, numpy=
array([[-9, -8,  3],
       [-6,  5, -4],
       [-3,  8, -1]])>

上面where()方法返回的结果在True的位置取值是a中对应位置元素的值，在False位置是b中对应元素的值。

# 4 维度变换

# 4.1 reshape()

numpy中的ndarray数组有个一reshape()方法，用来改变数组的shape，TensorFlow中的reshape()方法，功能也是一样的，不过TensorFlow中的reshape()没有绑定到tensor中：

In [200]:
a = tf.ones([2,3,4])

In [201]:
a.shape

TensorShape([2, 3, 4])

In [202]:
a

<tf.Tensor: id=569, shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [203]:
b = tf.reshape(a, [2, 2, 6])

In [204]:
b.shape

TensorShape([2, 2, 6])

In [205]:
b

<tf.Tensor: id=571, shape=(2, 2, 6), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]], dtype=float32)>

In [206]:
c = tf.reshape(a, [3, 2, 4])

In [207]:
c

<tf.Tensor: id=573, shape=(3, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

可以看到，在上面的例子中，通过reshape()方法可以很方便的改变tensor的形状，得到一个新的tensor，需要注意的是在进行维度变换时，数据的重量是不变的，上面的例子无论是[2,3,4]， [2, 2, 6]还是[3, 2, 4]都对应总量24，如果对应不上，就会产生异常。

# 3.2 转置：transpose()

transpose()方法提供了一种类似于装置的操作：

In [208]:
a = tf.constant([[1,2,3],[4,5,6]])

In [209]:
a.shape

TensorShape([2, 3])

In [210]:
b = tf.transpose(a)

In [211]:
b.shape

TensorShape([3, 2])

In [212]:
b

<tf.Tensor: id=576, shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

在默认情况下，transpose()方法会将所有维度按逆序方式完全转置，当然也可以通过perm参数执行需要转置的维度：

In [213]:
a=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [214]:
a

<tf.Tensor: id=577, shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [215]:
b = tf.transpose(a) # 不指定perm参数时，相当于tf.transpose(a, perm=[2, 1, 0])

In [216]:
b

<tf.Tensor: id=579, shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])>

In [217]:
c = tf.transpose(a, perm=[2, 1, 0])

In [218]:
c

<tf.Tensor: id=581, shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])>

In [219]:
d = tf.transpose(a, perm=[0, 2, 1]) # 第一个维度不做变换，对第二、第三维度进行转置

In [220]:
d

<tf.Tensor: id=583, shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6]],

       [[ 7, 10],
        [ 8, 11],
        [ 9, 12]]])>

# 3.3 添加维度：expand_dims()

In [221]:
a=tf.constant([[1,2,3],[4,5,6]])

In [222]:
a

<tf.Tensor: id=584, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [223]:
tf.expand_dims(a, axis=0)

<tf.Tensor: id=586, shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]])>

In [224]:
tf.expand_dims(a, axis=1)

<tf.Tensor: id=588, shape=(2, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]]])>

In [225]:
tf.expand_dims(a, axis=-1)

<tf.Tensor: id=590, shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])>

In [226]:
tf.expand_dims(a, axis=2)

<tf.Tensor: id=592, shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])>

expand_dims()方法添加维度时，通过axis参数指定添加维度的位置，正数表示从前往后数，负数表示从后往前数。

# 3.4 压缩维度：squeeze()

squeeze()方法与expand_dims()方法作用刚好相反，其作用是删除张量中dim为1的维度：

In [227]:
a = tf.ones([1,3,1,2])

In [228]:
a

<tf.Tensor: id=595, shape=(1, 3, 1, 2), dtype=float32, numpy=
array([[[[1., 1.]],

        [[1., 1.]],

        [[1., 1.]]]], dtype=float32)>

In [229]:
tf.squeeze(a)


<tf.Tensor: id=596, shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>