In [1]:
import tensorflow as tf

#  tf.reduce_sum(
#      input_tensor,
#      axis=None,
#      keepdims=None,
#      name=None,
#      reduction_indices=None,
#      keep_dims=None
#      )
#
#  Computes the sum of elements across dimensions of a tensor. (deprecated arguments)


#  1 2  4
#  8 16 32
#
#  x has a shape of (2, 3) (two rows and three columns):
#
#  The 0 axis in tensorflow is the rows, 1 axis is the columns.
#  By doing tf.reduce_sum(x, 0) the tensor is reduced along the first dimension
#  (rows), so the result is [1, 2, 4] + [8, 16, 32] = [9, 18, 32].
#
#  By doing tf.reduce_sum(x, 1) the tensor is reduced along the second dimension
#  (columns), so the result is [1, 9] + [2, 16] + [4, 32] = [7, 56].

x = tf.constant([[1, 2, 4], [8, 16, 32]])
print(tf.reduce_sum(x, 0))  # [ 9 18 36]
print(tf.reduce_sum(x, 1))  # [ 7 56]
print(tf.reduce_sum(x, [0, 1]))  # 63
print(tf.reduce_sum(x, 1, keepdims=True)) # [[ 7]
                                       #  [56]]




tf.Tensor([ 9 18 36], shape=(3,), dtype=int32)
tf.Tensor([ 7 56], shape=(2,), dtype=int32)
tf.Tensor(63, shape=(), dtype=int32)
tf.Tensor(
[[ 7]
 [56]], shape=(2, 1), dtype=int32)
